export const SAMPLE_NAMES_12 = [
  'Maria Santos',
  'John Miller',
  'David Chen',
  'Angela Davis',
  'Michael Scott',
  'Sarah Connor',
  'Carlos Rodriguez',
  'Emma Watson',
  'James Wilson',
  'Olivia Taylor',
  'Lucas Silva',
  'Sophia Martinez',
];

export const SAMPLE_NAMES_30 = [
  'Maria Santos',
  'John Miller',
  'David Chen',
  'Angela Davis',
  'Michael Scott',
  'Sarah Connor',
  'Carlos Rodriguez',
  'Emma Watson',
  'James Wilson',
  'Olivia Taylor',
  'Lucas Silva',
  'Sophia Martinez',
  'Alexander Bell',
  'Grace Hopper',
  'Liam Johnson',
  'Chloe Bennett',
  'Noah Williams',
  'Isabella Garcia',
  'Ethan Brown',
  'Mia Robinson',
  'Mason Clark',
  'Harper Lewis',
  'Benjamin Lee',
  'Evelyn Walker',
  'Daniel Hall',
  'Aria Allen',
  'Henry Young',
  'Scarlett King',
  'Jack Wright',
  'Victoria Scott',
];

export const SAMPLE_NAMES_100 = [
  'Maria Santos', 'John Miller', 'David Chen', 'Angela Davis', 'Michael Scott',
  'Sarah Connor', 'Carlos Rodriguez', 'Emma Watson', 'James Wilson', 'Olivia Taylor',
  'Lucas Silva', 'Sophia Martinez', 'Alexander Bell', 'Grace Hopper', 'Liam Johnson',
  'Chloe Bennett', 'Noah Williams', 'Isabella Garcia', 'Ethan Brown', 'Mia Robinson',
  'Mason Clark', 'Harper Lewis', 'Benjamin Lee', 'Evelyn Walker', 'Daniel Hall',
  'Aria Allen', 'Henry Young', 'Scarlett King', 'Jack Wright', 'Victoria Scott',
  'Logan Green', 'Luna Adams', 'Samuel Baker', 'Zoe Gonzalez', 'Sebastian Nelson',
  'Penelope Carter', 'Owen Mitchell', 'Riley Perez', 'Matthew Roberts', 'Layla Turner',
  'Julian Phillips', 'Nora Campbell', 'Levi Parker', 'Lily Evans', 'David Edwards',
  'Eleanor Collins', 'Joseph Stewart', 'Hannah Sanchez', 'Carter Morris', 'Lillian Rogers',
  'Wyatt Reed', 'Addison Cook', 'Jayden Morgan', 'Aubrey Bell', 'Gabriel Murphy',
  'Ellie Bailey', 'Anthony Rivera', 'Stella Cooper', 'Dylan Richardson', 'Natalie Cox',
  'Leo Howard', 'Violet Ward', 'Jaxon Torres', 'Aurora Peterson', 'Julian Gray',
  'Savannah Ramirez', 'Christopher James', 'Brooklyn Watson', 'Joshua Brooks', 'Bella Kelly',
  'Andrew Sanders', 'Claire Price', 'Lincoln Bennett', 'Skylar Wood', 'Mateo Barnes',
  'Lucy Ross', 'Ryan Henderson', 'Paisley Coleman', 'Nathan Jenkins', 'Everly Perry',
  'Adrian Powell', 'Anna Long', 'Christian Patterson', 'Caroline Hughes', 'Maverick Flores',
  'Nova Washington', 'Nicholas Butler', 'Genesis Simmons', 'Dominic Foster', 'Emilia Gonzales',
  'Austin Bryant', 'Kennedy Alexander', 'Adam Russell', 'Maya Griffin', 'Ian Diaz',
  'Madelyn Hayes', 'Elias Myers', 'Elena Ford', 'Colton Hamilton', 'Naomi Graham'
];
